import type { Quote } from "./types";

export const seedQuote: Quote = {
  reference: "ATR-2026-0184",
  client: "Sarah & Michael Johnson",
  trip: "Kenya + Zanzibar",
  dates: "12–22 October 2026",
  advisor: "Brownell Travel · 10%",
  pax: 2,
  clientCeiling: 25200,
  currency: "USD",
  lines: [
    {
      id: "acc-1",
      section: "ACCOMMODATION",
      service: "Hemingways Nairobi · Deluxe",
      supplier: "Hemingways Collection",
      dates: "12–13 Oct",
      units: "1 rm x 1 nt",
      basis: "per_unit",
      nett: 487,
      vatPct: 16,
      commPct: 10,
      mrkpPct: 18,
      confirmed: true,
      rate: {
        document: "2026 FIT contract",
        note: "Read from the current signed rate contract and unchanged since it was verified.",
        confidence: "high",
      },
    },
    {
      id: "acc-2",
      section: "ACCOMMODATION",
      service: "Angama Mara · Tented Suite",
      supplier: "Angama",
      dates: "13–16 Oct",
      units: "1 ste x 3 nt",
      basis: "per_unit",
      nett: 5940,
      vatPct: 16,
      commPct: 10,
      mrkpPct: 18,
      confirmed: true,
      rate: {
        document: "2026 rate letter, page 3",
        note: "Peak-season rate applied from 1 October. $340 a night above the June quote.",
        confidence: "high",
      },
    },
    {
      id: "acc-3",
      section: "ACCOMMODATION",
      service: "Zuri Zanzibar · Beach Villa",
      supplier: "Zuri Zanzibar",
      dates: "16–21 Oct",
      units: "1 vil x 5 nt",
      basis: "per_unit",
      nett: 5238,
      vatPct: 18,
      commPct: 10,
      mrkpPct: 18,
      confirmed: false,
      rate: {
        document: "Supplier portal",
        note: "Held on the supplier portal for 48 hours pending deposit. Price firm while the hold stands.",
        confidence: "high",
      },
    },
    {
      id: "acc-4",
      section: "ACCOMMODATION",
      service: "Zuri Zanzibar · Sunset Suite",
      supplier: "Zuri Zanzibar",
      dates: "16–21 Oct",
      units: "1 ste x 5 nt",
      basis: "per_unit",
      // No contracted rate has been found for this room type.
      nett: null,
      vatPct: 18,
      commPct: 10,
      mrkpPct: 18,
      confirmed: false,
      rate: {
        document: "—",
        note: "No contracted rate on file for this room type. Emailed the supplier 31 hours ago, no reply yet.",
        confidence: "low",
      },
    },
    {
      id: "trn-1",
      section: "TRANSPORT",
      service: "Arrival transfer · JKIA to Hemingways",
      supplier: "Nairobi Executive Transfers",
      dates: "12 Oct",
      units: "1 veh",
      basis: "per_unit",
      nett: 380,
      vatPct: 16,
      commPct: 10,
      mrkpPct: 18,
      confirmed: true,
      rate: {
        document: "2026 tariff",
        note: "Read from the current signed rate contract and unchanged since it was verified.",
        confidence: "high",
      },
    },
    {
      id: "trn-2",
      section: "TRANSPORT",
      service: "Light aircraft · Nairobi to Mara",
      supplier: "Safarilink",
      dates: "13 Oct",
      units: "2 pax",
      basis: "per_person",
      nett: 1240,
      vatPct: 16,
      commPct: 10,
      mrkpPct: 18,
      confirmed: true,
      rate: {
        document: "2026 published fares",
        note: "Published fare, seats not yet ticketed.",
        confidence: "high",
      },
    },
    {
      id: "trn-3",
      section: "TRANSPORT",
      service: "Light aircraft · Mara to Zanzibar",
      supplier: "Safarilink",
      dates: "16 Oct",
      units: "2 pax",
      basis: "per_person",
      nett: 1980,
      vatPct: 16,
      commPct: 10,
      // A consultant discounted this line to bring the trip under the ceiling.
      mrkpPct: -15,
      confirmed: true,
      rate: {
        document: "2026 published fares",
        note: "Cross-border charter. Discount applied by the consultant to hold the trip under budget.",
        confidence: "high",
      },
    },
    {
      id: "trn-4",
      section: "TRANSPORT",
      service: "Departure transfer · Zuri to ZNZ",
      supplier: "Zanzibar Island Transfers",
      dates: "21 Oct",
      units: "1 veh",
      basis: "per_unit",
      nett: 295,
      vatPct: 18,
      commPct: 10,
      mrkpPct: 18,
      confirmed: false,
      rate: {
        document: "2025 tariff",
        note: "2025 tariff carried forward. 2026 rates not yet released by the operator.",
        confidence: "low",
      },
    },
    {
      id: "act-1",
      section: "ACTIVITIES",
      service: "Balloon safari · Governors",
      supplier: "Governors Balloon Safaris",
      dates: "15 Oct",
      units: "2 pax",
      basis: "per_person",
      nett: 1150,
      vatPct: 16,
      commPct: 10,
      mrkpPct: 18,
      confirmed: false,
      rate: {
        document: "2026 tariff",
        note: "Client named this in the brief. Availability requested, no reply for 31 hours.",
        confidence: "medium",
      },
    },
    {
      id: "act-2",
      section: "ACTIVITIES",
      service: "Spice tour · private guide",
      supplier: "Zanzibar Heritage Tours",
      dates: "19 Oct",
      units: "2 pax",
      basis: "per_person",
      nett: 180,
      vatPct: 18,
      commPct: 10,
      mrkpPct: 18,
      confirmed: true,
      rate: {
        document: "2026 tariff",
        note: "Read from the current signed rate contract and unchanged since it was verified.",
        confidence: "high",
      },
    },
  ],
};
